<?php
/*
==============================================================================

	Copyright (c) 2018 Marc Augier

	For a full list of contributors, see "credits.txt".
	The full license can be read in "license.txt".

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	See the GNU General Public License for more details.

	Contact: m.augier@me.com
==============================================================================
*/

$servername = "localhost";
$username = "<user>";
$password = "<pass>";
$dbname = "drinks";
?>
